// The 175 App Store storefronts (from ASC /v1/territories), with approximate map centroids.
export interface Territory {
  code: string
  alpha3: string
  name: string
  currency: string
  lat: number
  lng: number
}

export const TERRITORIES: Territory[] = [
  { code: 'AF', alpha3: 'AFG', name: "Afghanistan", currency: 'USD', lat: 33.86, lng: 66.09 },
  { code: 'AO', alpha3: 'AGO', name: "Angola", currency: 'USD', lat: -12.29, lng: 17.50 },
  { code: 'AI', alpha3: 'AIA', name: "Anguilla", currency: 'USD', lat: 18.22, lng: -63.07 },
  { code: 'AL', alpha3: 'ALB', name: "Albania", currency: 'USD', lat: 41.14, lng: 20.03 },
  { code: 'AE', alpha3: 'ARE', name: "United Arab Emirates", currency: 'AED', lat: 23.87, lng: 54.21 },
  { code: 'AR', alpha3: 'ARG', name: "Argentina", currency: 'USD', lat: -35.22, lng: -65.15 },
  { code: 'AM', alpha3: 'ARM', name: "Armenia", currency: 'USD', lat: 40.22, lng: 45.00 },
  { code: 'AG', alpha3: 'ATG', name: "Antigua & Barbuda", currency: 'USD', lat: 17.08, lng: -61.80 },
  { code: 'AU', alpha3: 'AUS', name: "Australia", currency: 'AUD', lat: -25.56, lng: 134.38 },
  { code: 'AT', alpha3: 'AUT', name: "Austria", currency: 'EUR', lat: 47.61, lng: 14.08 },
  { code: 'AZ', alpha3: 'AZE', name: "Azerbaijan", currency: 'USD', lat: 40.28, lng: 47.68 },
  { code: 'BE', alpha3: 'BEL', name: "Belgium", currency: 'EUR', lat: 50.65, lng: 4.58 },
  { code: 'BJ', alpha3: 'BEN', name: "Benin", currency: 'USD', lat: 9.65, lng: 2.34 },
  { code: 'BF', alpha3: 'BFA', name: "Burkina Faso", currency: 'USD', lat: 12.31, lng: -1.78 },
  { code: 'BG', alpha3: 'BGR', name: "Bulgaria", currency: 'EUR', lat: 42.75, lng: 25.20 },
  { code: 'BH', alpha3: 'BHR', name: "Bahrain", currency: 'USD', lat: 26.07, lng: 50.56 },
  { code: 'BS', alpha3: 'BHS', name: "Bahamas", currency: 'USD', lat: 24.51, lng: -77.92 },
  { code: 'BA', alpha3: 'BIH', name: "Bosnia & Herzegovina", currency: 'EUR', lat: 44.18, lng: 17.82 },
  { code: 'BY', alpha3: 'BLR', name: "Belarus", currency: 'USD', lat: 53.51, lng: 27.98 },
  { code: 'BZ', alpha3: 'BLZ', name: "Belize", currency: 'USD', lat: 17.20, lng: -88.70 },
  { code: 'BM', alpha3: 'BMU', name: "Bermuda", currency: 'USD', lat: 32.31, lng: -64.76 },
  { code: 'BO', alpha3: 'BOL', name: "Bolivia", currency: 'USD', lat: -16.73, lng: -64.64 },
  { code: 'BR', alpha3: 'BRA', name: "Brazil", currency: 'BRL', lat: -10.81, lng: -53.05 },
  { code: 'BB', alpha3: 'BRB', name: "Barbados", currency: 'USD', lat: 13.19, lng: -59.54 },
  { code: 'BN', alpha3: 'BRN', name: "Brunei", currency: 'USD', lat: 4.69, lng: 114.92 },
  { code: 'BT', alpha3: 'BTN', name: "Bhutan", currency: 'USD', lat: 27.43, lng: 90.47 },
  { code: 'BW', alpha3: 'BWA', name: "Botswana", currency: 'USD', lat: -22.10, lng: 23.77 },
  { code: 'CA', alpha3: 'CAN', name: "Canada", currency: 'CAD', lat: 56.13, lng: -106.35 },
  { code: 'CH', alpha3: 'CHE', name: "Switzerland", currency: 'CHF', lat: 46.79, lng: 8.12 },
  { code: 'CL', alpha3: 'CHL', name: "Chile", currency: 'CLP', lat: -35.68, lng: -71.54 },
  { code: 'CN', alpha3: 'CHN', name: "China", currency: 'CNY', lat: 36.61, lng: 103.87 },
  { code: 'CI', alpha3: 'CIV', name: "Côte d’Ivoire", currency: 'USD', lat: 7.55, lng: -5.61 },
  { code: 'CM', alpha3: 'CMR', name: "Cameroon", currency: 'USD', lat: 5.66, lng: 12.61 },
  { code: 'CD', alpha3: 'COD', name: "Congo - Kinshasa", currency: 'USD', lat: -2.85, lng: 23.58 },
  { code: 'CG', alpha3: 'COG', name: "Congo - Brazzaville", currency: 'USD', lat: -0.84, lng: 15.13 },
  { code: 'CO', alpha3: 'COL', name: "Colombia", currency: 'COP', lat: 3.93, lng: -73.08 },
  { code: 'CV', alpha3: 'CPV', name: "Cape Verde", currency: 'USD', lat: 15.12, lng: -23.60 },
  { code: 'CR', alpha3: 'CRI', name: "Costa Rica", currency: 'USD', lat: 9.97, lng: -84.18 },
  { code: 'KY', alpha3: 'CYM', name: "Cayman Islands", currency: 'USD', lat: 19.31, lng: -81.25 },
  { code: 'CY', alpha3: 'CYP', name: "Cyprus", currency: 'EUR', lat: 34.91, lng: 33.04 },
  { code: 'CZ', alpha3: 'CZE', name: "Czechia", currency: 'CZK', lat: 49.78, lng: 15.33 },
  { code: 'DE', alpha3: 'DEU', name: "Germany", currency: 'EUR', lat: 51.13, lng: 10.29 },
  { code: 'DM', alpha3: 'DMA', name: "Dominica", currency: 'USD', lat: 15.41, lng: -61.37 },
  { code: 'DK', alpha3: 'DNK', name: "Denmark", currency: 'DKK', lat: 56.22, lng: 9.31 },
  { code: 'DO', alpha3: 'DOM', name: "Dominican Republic", currency: 'USD', lat: 18.88, lng: -70.46 },
  { code: 'DZ', alpha3: 'DZA', name: "Algeria", currency: 'USD', lat: 28.19, lng: 2.60 },
  { code: 'EC', alpha3: 'ECU', name: "Ecuador", currency: 'USD', lat: -1.45, lng: -78.38 },
  { code: 'EG', alpha3: 'EGY', name: "Egypt", currency: 'EGP', lat: 26.51, lng: 29.84 },
  { code: 'ES', alpha3: 'ESP', name: "Spain", currency: 'EUR', lat: 40.35, lng: -3.62 },
  { code: 'EE', alpha3: 'EST', name: "Estonia", currency: 'EUR', lat: 58.64, lng: 25.82 },
  { code: 'FI', alpha3: 'FIN', name: "Finland", currency: 'EUR', lat: 64.50, lng: 26.21 },
  { code: 'FJ', alpha3: 'FJI', name: "Fiji", currency: 'USD', lat: -17.83, lng: 178.00 },
  { code: 'FR', alpha3: 'FRA', name: "France", currency: 'EUR', lat: 46.23, lng: 2.21 },
  { code: 'FM', alpha3: 'FSM', name: "Micronesia", currency: 'USD', lat: 6.88, lng: 158.22 },
  { code: 'GA', alpha3: 'GAB', name: "Gabon", currency: 'USD', lat: -0.65, lng: 11.69 },
  { code: 'GB', alpha3: 'GBR', name: "United Kingdom", currency: 'GBP', lat: 53.88, lng: -2.66 },
  { code: 'GE', alpha3: 'GEO', name: "Georgia", currency: 'USD', lat: 42.16, lng: 43.48 },
  { code: 'GH', alpha3: 'GHA', name: "Ghana", currency: 'USD', lat: 7.93, lng: -1.24 },
  { code: 'GM', alpha3: 'GMB', name: "Gambia", currency: 'USD', lat: 13.48, lng: -15.43 },
  { code: 'GW', alpha3: 'GNB', name: "Guinea-Bissau", currency: 'USD', lat: 12.02, lng: -15.11 },
  { code: 'GR', alpha3: 'GRC', name: "Greece", currency: 'EUR', lat: 39.34, lng: 22.56 },
  { code: 'GD', alpha3: 'GRD', name: "Grenada", currency: 'USD', lat: 12.12, lng: -61.68 },
  { code: 'GT', alpha3: 'GTM', name: "Guatemala", currency: 'USD', lat: 15.70, lng: -90.37 },
  { code: 'GY', alpha3: 'GUY', name: "Guyana", currency: 'USD', lat: 4.79, lng: -58.97 },
  { code: 'HK', alpha3: 'HKG', name: "Hong Kong SAR China", currency: 'HKD', lat: 22.32, lng: 114.17 },
  { code: 'HN', alpha3: 'HND', name: "Honduras", currency: 'USD', lat: 14.82, lng: -86.59 },
  { code: 'HR', alpha3: 'HRV', name: "Croatia", currency: 'EUR', lat: 45.02, lng: 16.57 },
  { code: 'HU', alpha3: 'HUN', name: "Hungary", currency: 'HUF', lat: 47.20, lng: 19.36 },
  { code: 'ID', alpha3: 'IDN', name: "Indonesia", currency: 'IDR', lat: -0.25, lng: 114.02 },
  { code: 'IN', alpha3: 'IND', name: "India", currency: 'INR', lat: 22.93, lng: 79.59 },
  { code: 'IE', alpha3: 'IRL', name: "Ireland", currency: 'EUR', lat: 53.18, lng: -8.01 },
  { code: 'IQ', alpha3: 'IRQ', name: "Iraq", currency: 'USD', lat: 33.04, lng: 43.76 },
  { code: 'IS', alpha3: 'ISL', name: "Iceland", currency: 'USD', lat: 65.07, lng: -18.76 },
  { code: 'IL', alpha3: 'ISR', name: "Israel", currency: 'ILS', lat: 31.48, lng: 35.00 },
  { code: 'IT', alpha3: 'ITA', name: "Italy", currency: 'EUR', lat: 43.47, lng: 12.22 },
  { code: 'JM', alpha3: 'JAM', name: "Jamaica", currency: 'USD', lat: 18.14, lng: -77.32 },
  { code: 'JO', alpha3: 'JOR', name: "Jordan", currency: 'USD', lat: 31.25, lng: 36.78 },
  { code: 'JP', alpha3: 'JPN', name: "Japan", currency: 'JPY', lat: 36.02, lng: 136.88 },
  { code: 'KZ', alpha3: 'KAZ', name: "Kazakhstan", currency: 'KZT', lat: 48.19, lng: 67.28 },
  { code: 'KE', alpha3: 'KEN', name: "Kenya", currency: 'USD', lat: 0.60, lng: 37.79 },
  { code: 'KG', alpha3: 'KGZ', name: "Kyrgyzstan", currency: 'USD', lat: 41.51, lng: 74.62 },
  { code: 'KH', alpha3: 'KHM', name: "Cambodia", currency: 'USD', lat: 12.68, lng: 104.88 },
  { code: 'KN', alpha3: 'KNA', name: "St. Kitts & Nevis", currency: 'USD', lat: 17.36, lng: -62.78 },
  { code: 'KR', alpha3: 'KOR', name: "South Korea", currency: 'KRW', lat: 36.43, lng: 127.82 },
  { code: 'KW', alpha3: 'KWT', name: "Kuwait", currency: 'USD', lat: 29.31, lng: 47.60 },
  { code: 'LA', alpha3: 'LAO', name: "Laos", currency: 'USD', lat: 18.44, lng: 103.75 },
  { code: 'LB', alpha3: 'LBN', name: "Lebanon", currency: 'USD', lat: 33.91, lng: 35.87 },
  { code: 'LR', alpha3: 'LBR', name: "Liberia", currency: 'USD', lat: 6.43, lng: -9.41 },
  { code: 'LY', alpha3: 'LBY', name: "Libya", currency: 'USD', lat: 27.00, lng: 17.97 },
  { code: 'LC', alpha3: 'LCA', name: "St. Lucia", currency: 'USD', lat: 13.91, lng: -60.98 },
  { code: 'LK', alpha3: 'LKA', name: "Sri Lanka", currency: 'USD', lat: 7.70, lng: 80.67 },
  { code: 'LT', alpha3: 'LTU', name: "Lithuania", currency: 'EUR', lat: 55.28, lng: 23.88 },
  { code: 'LU', alpha3: 'LUX', name: "Luxembourg", currency: 'EUR', lat: 49.77, lng: 5.97 },
  { code: 'LV', alpha3: 'LVA', name: "Latvia", currency: 'EUR', lat: 56.81, lng: 24.83 },
  { code: 'MO', alpha3: 'MAC', name: "Macao SAR China", currency: 'USD', lat: 22.20, lng: 113.54 },
  { code: 'MA', alpha3: 'MAR', name: "Morocco", currency: 'USD', lat: 29.89, lng: -8.42 },
  { code: 'MD', alpha3: 'MDA', name: "Moldova", currency: 'USD', lat: 47.20, lng: 28.41 },
  { code: 'MG', alpha3: 'MDG', name: "Madagascar", currency: 'USD', lat: -19.36, lng: 46.69 },
  { code: 'MV', alpha3: 'MDV', name: "Maldives", currency: 'USD', lat: 3.20, lng: 73.22 },
  { code: 'MX', alpha3: 'MEX', name: "Mexico", currency: 'MXN', lat: 23.94, lng: -102.58 },
  { code: 'MK', alpha3: 'MKD', name: "North Macedonia", currency: 'USD', lat: 41.61, lng: 21.70 },
  { code: 'ML', alpha3: 'MLI', name: "Mali", currency: 'USD', lat: 17.27, lng: -3.54 },
  { code: 'MT', alpha3: 'MLT', name: "Malta", currency: 'EUR', lat: 35.89, lng: 14.44 },
  { code: 'MM', alpha3: 'MMR', name: "Myanmar (Burma)", currency: 'USD', lat: 21.02, lng: 96.51 },
  { code: 'ME', alpha3: 'MNE', name: "Montenegro", currency: 'EUR', lat: 42.79, lng: 19.29 },
  { code: 'MN', alpha3: 'MNG', name: "Mongolia", currency: 'USD', lat: 46.82, lng: 102.95 },
  { code: 'MZ', alpha3: 'MOZ', name: "Mozambique", currency: 'USD', lat: -17.23, lng: 35.47 },
  { code: 'MR', alpha3: 'MRT', name: "Mauritania", currency: 'USD', lat: 20.21, lng: -10.33 },
  { code: 'MS', alpha3: 'MSR', name: "Montserrat", currency: 'USD', lat: 16.74, lng: -62.19 },
  { code: 'MU', alpha3: 'MUS', name: "Mauritius", currency: 'USD', lat: -20.35, lng: 57.55 },
  { code: 'MW', alpha3: 'MWI', name: "Malawi", currency: 'USD', lat: -13.17, lng: 34.19 },
  { code: 'MY', alpha3: 'MYS', name: "Malaysia", currency: 'MYR', lat: 3.55, lng: 114.68 },
  { code: 'NA', alpha3: 'NAM', name: "Namibia", currency: 'USD', lat: -22.10, lng: 17.16 },
  { code: 'NE', alpha3: 'NER', name: "Niger", currency: 'USD', lat: 17.35, lng: 9.32 },
  { code: 'NG', alpha3: 'NGA', name: "Nigeria", currency: 'NGN', lat: 9.55, lng: 8.00 },
  { code: 'NI', alpha3: 'NIC', name: "Nicaragua", currency: 'USD', lat: 12.85, lng: -85.02 },
  { code: 'NL', alpha3: 'NLD', name: "Netherlands", currency: 'EUR', lat: 52.30, lng: 5.51 },
  { code: 'NO', alpha3: 'NOR', name: "Norway", currency: 'NOK', lat: 60.47, lng: 8.47 },
  { code: 'NP', alpha3: 'NPL', name: "Nepal", currency: 'USD', lat: 28.24, lng: 84.01 },
  { code: 'NR', alpha3: 'NRU', name: "Nauru", currency: 'USD', lat: -0.52, lng: 166.93 },
  { code: 'NZ', alpha3: 'NZL', name: "New Zealand", currency: 'NZD', lat: -43.99, lng: 170.51 },
  { code: 'OM', alpha3: 'OMN', name: "Oman", currency: 'USD', lat: 20.58, lng: 56.10 },
  { code: 'PK', alpha3: 'PAK', name: "Pakistan", currency: 'PKR', lat: 29.97, lng: 69.41 },
  { code: 'PA', alpha3: 'PAN', name: "Panama", currency: 'USD', lat: 8.53, lng: -80.11 },
  { code: 'PE', alpha3: 'PER', name: "Peru", currency: 'PEN', lat: -9.19, lng: -74.39 },
  { code: 'PH', alpha3: 'PHL', name: "Philippines", currency: 'PHP', lat: 15.75, lng: 121.54 },
  { code: 'PW', alpha3: 'PLW', name: "Palau", currency: 'USD', lat: 7.51, lng: 134.58 },
  { code: 'PG', alpha3: 'PNG', name: "Papua New Guinea", currency: 'USD', lat: -6.65, lng: 144.33 },
  { code: 'PL', alpha3: 'POL', name: "Poland", currency: 'PLN', lat: 52.15, lng: 19.31 },
  { code: 'PT', alpha3: 'PRT', name: "Portugal", currency: 'EUR', lat: 39.63, lng: -8.06 },
  { code: 'PY', alpha3: 'PRY', name: "Paraguay", currency: 'USD', lat: -23.25, lng: -58.39 },
  { code: 'QA', alpha3: 'QAT', name: "Qatar", currency: 'QAR', lat: 25.32, lng: 51.18 },
  { code: 'RO', alpha3: 'ROU', name: "Romania", currency: 'RON', lat: 45.86, lng: 24.94 },
  { code: 'RU', alpha3: 'RUS', name: "Russia", currency: 'RUB', lat: 61.52, lng: 105.32 },
  { code: 'RW', alpha3: 'RWA', name: "Rwanda", currency: 'USD', lat: -2.01, lng: 29.92 },
  { code: 'SA', alpha3: 'SAU', name: "Saudi Arabia", currency: 'SAR', lat: 24.12, lng: 44.52 },
  { code: 'SN', alpha3: 'SEN', name: "Senegal", currency: 'USD', lat: 14.35, lng: -14.51 },
  { code: 'SG', alpha3: 'SGP', name: "Singapore", currency: 'SGD', lat: 1.35, lng: 103.82 },
  { code: 'SB', alpha3: 'SLB', name: "Solomon Islands", currency: 'USD', lat: -7.90, lng: 159.10 },
  { code: 'SL', alpha3: 'SLE', name: "Sierra Leone", currency: 'USD', lat: 8.53, lng: -11.80 },
  { code: 'SV', alpha3: 'SLV', name: "El Salvador", currency: 'USD', lat: 13.73, lng: -88.87 },
  { code: 'RS', alpha3: 'SRB', name: "Serbia", currency: 'EUR', lat: 44.23, lng: 20.82 },
  { code: 'ST', alpha3: 'STP', name: "São Tomé & Príncipe", currency: 'USD', lat: 0.19, lng: 6.61 },
  { code: 'SR', alpha3: 'SUR', name: "Suriname", currency: 'USD', lat: 4.12, lng: -55.91 },
  { code: 'SK', alpha3: 'SVK', name: "Slovakia", currency: 'EUR', lat: 48.73, lng: 19.51 },
  { code: 'SI', alpha3: 'SVN', name: "Slovenia", currency: 'EUR', lat: 46.13, lng: 14.94 },
  { code: 'SE', alpha3: 'SWE', name: "Sweden", currency: 'SEK', lat: 62.81, lng: 16.60 },
  { code: 'SZ', alpha3: 'SWZ', name: "Eswatini", currency: 'USD', lat: -26.49, lng: 31.40 },
  { code: 'SC', alpha3: 'SYC', name: "Seychelles", currency: 'USD', lat: -4.68, lng: 55.49 },
  { code: 'TC', alpha3: 'TCA', name: "Turks & Caicos Islands", currency: 'USD', lat: 21.69, lng: -71.80 },
  { code: 'TD', alpha3: 'TCD', name: "Chad", currency: 'USD', lat: 15.33, lng: 18.58 },
  { code: 'TH', alpha3: 'THA', name: "Thailand", currency: 'THB', lat: 15.02, lng: 101.01 },
  { code: 'TJ', alpha3: 'TJK', name: "Tajikistan", currency: 'USD', lat: 38.58, lng: 71.03 },
  { code: 'TM', alpha3: 'TKM', name: "Turkmenistan", currency: 'USD', lat: 39.09, lng: 59.28 },
  { code: 'TO', alpha3: 'TON', name: "Tonga", currency: 'USD', lat: -21.18, lng: -175.20 },
  { code: 'TT', alpha3: 'TTO', name: "Trinidad & Tobago", currency: 'USD', lat: 10.43, lng: -61.33 },
  { code: 'TN', alpha3: 'TUN', name: "Tunisia", currency: 'USD', lat: 34.17, lng: 9.53 },
  { code: 'TR', alpha3: 'TUR', name: "Türkiye", currency: 'TRY', lat: 38.99, lng: 35.39 },
  { code: 'TW', alpha3: 'TWN', name: "Taiwan", currency: 'TWD', lat: 23.74, lng: 120.97 },
  { code: 'TZ', alpha3: 'TZA', name: "Tanzania", currency: 'TZS', lat: -6.26, lng: 34.75 },
  { code: 'UG', alpha3: 'UGA', name: "Uganda", currency: 'USD', lat: 1.30, lng: 32.36 },
  { code: 'UA', alpha3: 'UKR', name: "Ukraine", currency: 'USD', lat: 48.97, lng: 31.37 },
  { code: 'UY', alpha3: 'URY', name: "Uruguay", currency: 'USD', lat: -32.78, lng: -56.00 },
  { code: 'US', alpha3: 'USA', name: "United States", currency: 'USD', lat: 39.50, lng: -98.35 },
  { code: 'UZ', alpha3: 'UZB', name: "Uzbekistan", currency: 'USD', lat: 41.75, lng: 63.20 },
  { code: 'VC', alpha3: 'VCT', name: "St. Vincent & Grenadines", currency: 'USD', lat: 13.25, lng: -61.20 },
  { code: 'VE', alpha3: 'VEN', name: "Venezuela", currency: 'USD', lat: 7.16, lng: -66.16 },
  { code: 'VG', alpha3: 'VGB', name: "British Virgin Islands", currency: 'USD', lat: 18.42, lng: -64.64 },
  { code: 'VN', alpha3: 'VNM', name: "Vietnam", currency: 'VND', lat: 16.66, lng: 106.29 },
  { code: 'VU', alpha3: 'VUT', name: "Vanuatu", currency: 'USD', lat: -15.22, lng: 166.91 },
  { code: 'XK', alpha3: 'XKS', name: "Kosovo", currency: 'EUR', lat: 42.60, lng: 20.90 },
  { code: 'YE', alpha3: 'YEM', name: "Yemen", currency: 'USD', lat: 15.91, lng: 47.54 },
  { code: 'ZA', alpha3: 'ZAF', name: "South Africa", currency: 'ZAR', lat: -28.96, lng: 25.12 },
  { code: 'ZM', alpha3: 'ZMB', name: "Zambia", currency: 'USD', lat: -13.40, lng: 27.73 },
  { code: 'ZW', alpha3: 'ZWE', name: "Zimbabwe", currency: 'USD', lat: -18.91, lng: 29.79 },
]

export const TERRITORY_BY_CODE: Record<string, Territory> = Object.fromEntries(TERRITORIES.map((t) => [t.code, t]))

export function territoryName(code: string): string {
  return TERRITORY_BY_CODE[code]?.name ?? code
}

export function countryToFlag(code: string): string {
  if (!code || code.length !== 2) return ''
  return code.toUpperCase().replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
}
